#version 430

layout(local_size_x = 1, local_size_y = 1) in;
layout(rgba16f, binding = 0) uniform writeonly image2D img_output;
layout(rgba16f, binding = 1) uniform readonly image2D img_input;

void main() {

  // get index in global work group i.e x,y position
  ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);

  vec4 pixel = imageLoad(img_input, pixel_coords);

  // output to a specific pixel in the image
  imageStore(img_output, pixel_coords, pixel);

}